<a href="https://colab.research.google.com/github/zhoujiuzhou9/tensorFlow/blob/V1/TensorFlow_with_GPU-3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
import tensorflow as tf
import numpy as np
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
print(tf.__version__)

a=tf.ones([1,5,5,3])
print(a[0][0])



2.8.2
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(5, 3), dtype=float32)


In [5]:
import os
import tensorflow as tf
import numpy as np
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
print(tf.__version__)

a=tf.ones([1,5,5,3])
print(a[0][0][0])

print(a[0,:,:,:])

2.8.2
tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)
tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]], shape=(5, 5, 3), dtype=float32)


In [6]:
a = tf.ones([4, 35, 8])
b = tf.gather_nd(a, [[0, 0], [1, 1]])
print(a.shape)


(4, 35, 8)


In [7]:
import os
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, optimizers, datasets

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

(x, y), (x_val, y_val) = datasets.mnist.load_data()
x = tf.convert_to_tensor(x, dtype=tf.float32) / 255.
y = tf.convert_to_tensor(y, dtype=tf.int32)
y = tf.one_hot(y, depth=10)
print(x.shape, y.shape)
train_dataset = tf.data.Dataset.from_tensor_slices((x, y))
train_dataset = train_dataset.batch(200)

model = keras.Sequential([
    layers.Dense(512, activation='relu'),
    layers.Dense(256, activation='relu'),
    layers.Dense(10)])

optimizer = optimizers.SGD(learning_rate=0.001)


def train_epoch(epoch):
    # Step4.loop
    for step, (x, y) in enumerate(train_dataset):

        with tf.GradientTape() as tape:
            # [b, 28, 28] => [b, 784]
            x = tf.reshape(x, (-1, 28 * 28))
            # Step1. compute output
            # [b, 784] => [b, 10]
            out = model(x)
            # Step2. compute loss
            loss = tf.reduce_sum(tf.square(out - y)) / x.shape[0]

        # Step3. optimize and update w1, w2, w3, b1, b2, b3
        grads = tape.gradient(loss, model.trainable_variables)
        # w' = w - lr * grad
        optimizer.apply_gradients(zip(grads, model.trainable_variables))

        if step % 100 == 0:
            print(epoch, step, 'loss:', loss.numpy())


def train():
    for epoch in range(30):
        train_epoch(epoch)


if __name__ == '__main__':
    train()

11501568/11490434 [==============================] - 0s 0us/step
(60000, 28, 28) (60000, 10)
0 0 loss: 1.6208457
0 100 loss: 0.9526868
0 200 loss: 0.7700283
1 0 loss: 0.7078283
1 100 loss: 0.69496673
1 200 loss: 0.5971144
2 0 loss: 0.5806367
2 100 loss: 0.60655874
2 200 loss: 0.52528185
3 0 loss: 0.5178297
3 100 loss: 0.55543846
3 200 loss: 0.482154
4 0 loss: 0.47777492
4 100 loss: 0.5197071
4 200 loss: 0.45158893
5 0 loss: 0.44926926
5 100 loss: 0.49264672
5 200 loss: 0.42803946
6 0 loss: 0.42691112
6 100 loss: 0.47065076
6 200 loss: 0.408868
7 0 loss: 0.40828735
7 100 loss: 0.45205152
7 200 loss: 0.39264083
8 0 loss: 0.39244282
8 100 loss: 0.43588996
8 200 loss: 0.37861684
9 0 loss: 0.37861007
9 100 loss: 0.42159158
9 200 loss: 0.36610427
10 0 loss: 0.36643353
10 100 loss: 0.40882838
10 200 loss: 0.35487157
11 0 loss: 0.35547912
11 100 loss: 0.39737633
11 200 loss: 0.34483346
12 0 loss: 0.3455511
12 100 loss: 0.3871588
12 200 loss: 0.33576474
13 0 loss: 0.33638015
13 100 loss: 0.3779